---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
    driver_config:
      forward:
      - 8080:80
      - 8181:81


suites:
  - name: default
    run_list:
      - recipe[myapache::default]
    attributes:
      myapache:
        greeting: TestKitchen

